version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  # chrome:
  #   image: selenium/standalone-chrome-debug:latest
  #   ports:
  #     - "4444:4444"
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: circle_app_web_1
    ports:
      - '3000:3000'
    environment:
      JS_API_KEY: ${JS_API_KEY}
      GE_API_KEY: ${GE_API_KEY}
    depends_on:
      - db
      # - chrome
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
