version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: circle_app_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0
