version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/develop
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true
