version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: circle_app_web_1
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
