version: 2.1
jobs:
  # rubocop:
  #   working_directory: ~/circle_app
  #   docker:
  #     - image: circleci/ruby:2.5.9
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  #           - gemfiles-{{ .Branch }}-
  #           - gemfiles-master-
  #     - run: bundle config --local path vendor/bundle
  #     - run:
  #         name: bundle install
  #         command: bundle check || bundle install --jobs=8 --clean
  #     - run:
  #         name: Run rubocop
  #         command: bundle exec rubocop --parallel
  #     - save_cache:
  #         key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  #         paths:
  #           - vendor/bundle

  rspec:
    working_directory: ~/circle_app
    docker:
      - image: circleci/ruby:2.5.9-node-browsers
        environment:
          RAILS_ENV: test
          # POSTGES_HOST: db
      - image: circleci/postgres
        # environment:
        #   POSTGRES_DB: develop_test
        #   POSTGRES_USER: postgres
        #   POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: gem install bundler
      - run: bundle install
      - run: bundle update
      - run: yarn install
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Wait for the DB to start.
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load --trace
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

orbs:
  build-tools: circleci/build-tools@2.9.1
  jq: circleci/jq@2.2.0

workflows:
  version: 2
  build:
    jobs:
      - rspec
      # - rubocop
      # - rspec:
      #     requires:
      #       - rubocop
