version: 2.1
jobs:
  rubocop:
    working_directory: ~/circle_app
    docker:
      - image: circleci/ruby:2.5.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

orbs:
  build-tools: circleci/build-tools@2.9.1
  jq: circleci/jq@2.2.0

workflows:
  version: 2
  build:
    jobs:
      - rubocop
      # - rspec:
      #     requires:
      #       - rubocop
