# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'

# 開発環境向け
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

# 本番環境向け
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   host: localhost
#   username: circle
#   password: password01#
#   pool: 5

development:
  <<: *default
  database: develop_development

test:
  <<: *default
  database: develop_test

# production:
#   <<: *default
#   database: <%= Rails.application.credentials.db[:database] %>
#   username: <%= Rails.application.credentials.db[:username] %>
#   password: <%= Rails.application.credentials.db[:password] %>
#   socket: <%= Rails.application.credentials.db[:socket] %>

production:
  <<: *default
  database: postgres_app_db
  socket: /var/lib/mysql/mysql.sock
