# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  host: db
  database: develop_development

test:
  <<: *default
  # host: db
  host: localhost
  database: develop_test

production:
  <<: *default
  host: localhost
  database: postgres_app_db
  socket: /var/lib/mysql/mysql.sock
